kind = "web"
previewPath = "/"
title = "Replit Stripper"
version = "1.0.0"
id = "artifacts/replit-stripper"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19284

[services.development]
run = "pnpm --filter @workspace/replit-stripper run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/replit-stripper", "run", "build" ]
publicDir = "artifacts/replit-stripper/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19284"
BASE_PATH = "/"
